# src/plotting/plot_Cv.py
# With much help from ChatGPT
import numpy as np
import matplotlib as mpl
mpl.use("Agg") # to avoid wayland issues
import matplotlib.pyplot as plt
import json
from scipy.stats import linregress
import math
from pathlib import Path

# plotting style
plt.rcParams.update({
    'font.family': 'serif',
    'font.size': 14,
    'figure.figsize': (6, 4),
    'axes.titlesize': 14,
    'axes.labelsize': 15,
    'xtick.labelsize': 12,
    'ytick.labelsize': 12,
    'lines.linewidth': 2.0,
    'legend.fontsize': 15,
    'figure.dpi': 300,
})

# Finds project root
ROOT = Path(__file__).resolve().parents[2]

fig_dir = ROOT / "Project4/data/figures/"
fig_dir.mkdir(parents=True, exist_ok=True)
file_dir = ROOT / "Project4/data/outputs/"

# The rest of the code from here is generated by ChatGPT and simply modified
def plot_lattice_qr(lattice_file, out_file):
    
    data = []
    with open(lattice_file, "r") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            
            row = [int(ch) for ch in line]
            data.append(row)

    arr = np.array(data)

    fig, ax = plt.subplots(figsize=(4, 4))
    ax.imshow(1 - arr, cmap="binary", interpolation="nearest")
    ax.set_axis_off()
    ax.set_aspect("equal")
    fig.savefig(out_file, bbox_inches="tight", pad_inches=0)
    plt.close(fig)

if __name__ == "__main__":
    
    lattice_path = file_dir / "QR_40_T=2.377000.txt"
    qr_fig_path = fig_dir / "ising_lattice_qr.pdf"

    plot_lattice_qr(lattice_path, qr_fig_path)
    print(f"Saved QR-style lattice plot to {qr_fig_path}")